-- Load config
require("plugins")
require("mappings")
require("settings")
require("config/lsp")
require("config/treesitter")
require("config/dap")
require("config/dapui")
require("config/go")
require("config/neoterm")
require("config/lualine")
require("config/which-key")
require("config/telescope")
